version: "2.1"

services:

  mysql:
    image: mysql
    network_mode: "host"
    environment:
      MYSQL_DATABASE: 'esb-mock'
      MYSQL_USER: 'sa'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"